// <auto-generated />
using System;
using CollegeChemistryAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CollegeChemistryAPI.Migrations
{
    [DbContext(typeof(CollegeChemistryDbContext))]
    [Migration("20251121131317_SQLiteInitial")]
    partial class SQLiteInitial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.0");

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.Blogs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("cover_picture")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ispublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updated_by_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.Category", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("category_name")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ispublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updated_by_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.Lessons", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("category_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("content")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("cover_picture")
                        .HasColumnType("BLOB");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("description")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ispublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updated_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("youtube_video")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.MCQs", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ispublish")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("title")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updated_by_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("MCQs");
                });

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.Questions", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<char>("correct_option")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("created_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("created_by_id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("ispublish")
                        .HasColumnType("INTEGER");

                    b.Property<int>("mcq_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("option_a")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_b")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_c")
                        .HasColumnType("TEXT");

                    b.Property<string>("option_d")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("published_at")
                        .HasColumnType("TEXT");

                    b.Property<string>("question")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("updated_at")
                        .HasColumnType("TEXT");

                    b.Property<int?>("updated_by_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("CollegeChemistryLibrary.Entities.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .HasColumnType("TEXT");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
